### PR TITLE
Critical Spanish translation corrections

### PR DESCRIPTION
**Pull request by Flerex**
- Added missing translations
- Multiple corrections (really necessary) to the translations

### CODE REVIEW

**Comment by Galixte** [comment]
@phpbb-es, it's better?

**Comment by phpbb-es** [comment]
"Critical"... it's a "hard word".
If there are new lines (I understand a new version), and you can always improve a software or a translation, for me it would be simpler to not translate anything ... Or improve translations of others.

Best regards.

**Comment by Flerex** [comment]
I chose the word Critical because not only were there missing translations in the production version, but some of them didn't make any sense in Spanish. For example:

> Foro individual puede ser incluido o excluido cambiando su configuración en el PCA. <br /> Además, a través de la configuración de esta página, se puede permiten a los usuarios editar el propio cierta medida los aspectos

Most of the changes are mere tweaks tho. Some of them were simply to bring the translation closer in line with the English version.

**Comment by phpbb-es** [comment]
@Flerex 
True, that part if it is a "bad translation", and then the "mea culpa", sorry man. ;)

Merged @Sajaki  please.

**Pull request merged**
